task_info:
  save_dir: "./src/tasks_info"
  name: "train"


train_cfg:
  max_epoch: 200
  save_frequency: 5
  test_frequency: 5
  device: "cuda"

network:
  name: "resnet18"
  params:
      in_channels: 3
      out_channels: 136

optimizer:
  name: "adam"
  params:
    lr: 0.001
    betas: [0.9, 0.949]
    weight_decay: 0.0005

criterion:
  name: "WingLoss"
  params:
    w: 10
    eps: 2

scheduler:
  name: MultiStepLR
  params:
    milestones: [50, 100, 140,180]
    gamma: 0.1

train_dataset:
  dataset:
    ds_dir: "/mnt/e/WORK_DL/datasets/landmarks_task/Menpo/train"
    suffix: "[jp][pn]g"
    use_dlib_detector: False
    use_mask: True
    input_size: [96, 96]

  transforms:
    input_size: [96, 96]

train_dataloader:
  batch_size: 32
  shuffle: True
  num_workers: 0

val_dataset:
  dataset:
    ds_dir: "/mnt/e/WORK_DL/datasets/landmarks_task/Menpo/test"
    suffix: "[jp][pn]g"
    use_dlib_detector: False
    use_mask: True
    input_size: [96, 96]

  transforms:
    input_size: [256, 256]

val_dataloader:
  batch_size: 32
  shuffle: False
  num_workers: 0